const data = {
  userId: "62b6e5a570b50f13787c9898",
  academicYear: "2022-23",
  eMaterialUdemy: {
    pointsAlloted: 20,
    noOfActivity: 20,
    pointScored: 20,
    uploadProof: "proof.jpg",
  },
  eMaterialSatyabama: {
    pointsAlloted: 5,
    noOfActivity: 10,
    pointScored: 5,
    uploadProof: "proof2.jpg",
  },
  courseInEmergingArea: {
    pointsAlloted: 25,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  youtubeLec1: {
    pointsAlloted: 5,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  youtubeLec2: {
    pointsAlloted: 2,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  extraTeachingActivity: {
    pointsAlloted: 5,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  awards: {
    pointsAlloted: 50,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  memberInOtherAcadBoard: {
    pointsAlloted: 5,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  valueAddedProg: {
    pointsAlloted: 10,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  overAllContribution: {
    pointsAlloted: 10,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  evaluationOfExamPaper: {
    pointsAlloted: 5,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  mentorInHackathon: {
    pointsAlloted: 10,
    noOfActivity: 0,
    pointScored: 0,
    uploadProof: "",
  },
  totalScore: 0,
  status: { currStatus: "pending", statusMsg: ["pending"] },
  _id: "62b6ef2eb9e732176fe7cb39",
  __v: 0,
};
